server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
h2:
  console:
    enabled: true
build:
  version: "1.0"
management:
  endpoints:
    web:
      exposure:
        include: "*"
