spring:
  application:
    name: "configserver"
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-location: "file:///home//shantonu//course//config"
          #search-location: "classpath:/configserver"


server:
  port: 8071
